#!/usr/local/py_venv/pki_dev_p37/bin/python3.7
# EASY-INSTALL-ENTRY-SCRIPT: 'serverPKI','console_scripts','operate_serverPKI'
__requires__ = 'serverPKI'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('serverPKI', 'console_scripts', 'operate_serverPKI')()
    )
